deploy:
  provider: pages
  skip_cleanup: true
  github_token: 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  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: main
    
language: node_js
node_js:
  - "12"

cache:
  apt: true
  directories:
    - node_modules

# S: Build Lifecycle
install:
  - npm install


#before_script:
 # - npm install -g gulp

script:
  - hexo g --debug

after_script:
  - cd ./public
  - git init
  - git config user.name "sophiazmm"
  - git config user.email "zhangmm@cau.edu.cn"
  - git add .
  - git commit -m "Update docs"
  - git push --force --quiet "https://${myblog}@github.com/sophiazmm/sophiazmm.github.io.git" master:master
# E: Build LifeCycle

branches:
  only:
    - blog-source
    
env:
 global:
   - GH_REF:github.com/sophiazmm/sophiazmm.github.io.git
