language: node_js
node_js: stable

# S: Build Lifecycle
install:
  - npm install


#before_script:
 # - npm install -g gulp

script:
  - hexo g

after_script:
  - cd ./public
  - git init
  - git config user.name "sophiazmm"
  - git config user.email "zhangmm@cau.edu.cn"
  - git add .
  - git commit -m "Update docs"
  - git push --force --quiet "https://${myblog}@${GH_REF}" master:master
# E: Build LifeCycle

branches:
  only:
    - blog-source
<<<<<<< HEAD

cache:
  directories:
    - node_modules
    
env:
 global:
   - GH_REF:github.com/sophiazmm/sophiazmm.github.io.git
=======
env:
 global:
   - GH_REF:github.com/sophiazmm/sophiazmm.github.io.git
   
cache:
  directories:
    - node_modules
>>>>>>> 0c040fdc796354dde5f6ca9abf7e8d22599f0963
