language: node_js
node_js:
  - "12"

cache:
  apt: true
  directories:
    - node_modules

# S: Build Lifecycle
install:
  - npm install


#before_script:
 # - npm install -g gulp

script:
  - hexo g --debug

after_script:
  - cd ./public
  - git init
  - git config user.name "sophiazmm"
  - git config user.email "zhangmm@cau.edu.cn"
  - git add .
  - git commit -m "Update docs"
  - git push --force --quiet "https://${myblog}@github.com/sophiazmm/sophiazmm.github.io.git" master:master
# E: Build LifeCycle

branches:
  only:
    - blog-source
    
env:
 global:
   - GH_REF:github.com/sophiazmm/sophiazmm.github.io.git
   secure: {"lots-of-seemingly-random-characters"}
